const template = (opts: { body: string; initialState: string }) => {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Employee Directory</title>
        <meta name="description" content="Demonstrates how to dynamically generate images on the server">
        
      </head>
      <body>
        <div id="root">${opts.body}</div>
      </body>
      <script>
        window.__initialState = ${opts.initialState}
      </script>
      <!-- Client bundle generated by webpack -->
      <script src='/views/Server.js'></script>
    </html>
    `;
};

export default template;
