"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

const template = opts => {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Employee Directory</title>
        <meta name="description" content="Demonstrates how to dynamically generate images on the server">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="/assets/custom.css" />
      </head>
      <body>
        <div id="root">${opts.body}</div>
      </body>
      <script>
        window.__initialState = ${opts.initialState}
      </script>
      <!-- Client bundle generated by webpack -->
      <script src='/assets/client.bundle.js'></script>
    </html>
    `;
};

var _default = template;
exports.default = _default;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uLy4uL3NyYy93ZWIvbGliL3RlbXBsYXRlLnRzIl0sIm5hbWVzIjpbInRlbXBsYXRlIiwib3B0cyIsImJvZHkiLCJpbml0aWFsU3RhdGUiXSwibWFwcGluZ3MiOiI7Ozs7Ozs7QUFBQSxNQUFNQSxRQUFRLEdBQUlDLElBQUQsSUFBa0Q7QUFDakUsU0FBUTs7Ozs7Ozs7Ozs7O3lCQVllQSxJQUFJLENBQUNDLElBQUs7OztrQ0FHREQsSUFBSSxDQUFDRSxZQUFhOzs7OztLQWZsRDtBQXFCRCxDQXRCRDs7ZUF3QmVILFEiLCJzb3VyY2VzQ29udGVudCI6WyJjb25zdCB0ZW1wbGF0ZSA9IChvcHRzOiB7IGJvZHk6IHN0cmluZzsgaW5pdGlhbFN0YXRlOiBzdHJpbmcgfSkgPT4ge1xuICByZXR1cm4gYFxuICAgIDwhRE9DVFlQRSBodG1sPlxuICAgIDxodG1sPlxuICAgICAgPGhlYWQ+XG4gICAgICAgIDx0aXRsZT5FbXBsb3llZSBEaXJlY3Rvcnk8L3RpdGxlPlxuICAgICAgICA8bWV0YSBuYW1lPVwiZGVzY3JpcHRpb25cIiBjb250ZW50PVwiRGVtb25zdHJhdGVzIGhvdyB0byBkeW5hbWljYWxseSBnZW5lcmF0ZSBpbWFnZXMgb24gdGhlIHNlcnZlclwiPlxuICAgICAgICA8IS0tIEJvb3RzdHJhcCAtLT5cbiAgICAgICAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCJodHRwczovL21heGNkbi5ib290c3RyYXBjZG4uY29tL2Jvb3RzdHJhcC80LjQuMS9jc3MvYm9vdHN0cmFwLm1pbi5jc3NcIiBpbnRlZ3JpdHk9XCJzaGEzODQtVmtvbzh4NENHc08zK0hoeHY4VC9RNVBhWHRrS3R1NnVnNVRPZU5WNmdCaUZlV1BHRk45TXVoT2YyM1E5SWZqaFwiIGNyb3Nzb3JpZ2luPVwiYW5vbnltb3VzXCI+XG4gICAgICAgIDwhLS0gQ3VzdG9tIENTUyAtLT5cbiAgICAgICAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCIvYXNzZXRzL2N1c3RvbS5jc3NcIiAvPlxuICAgICAgPC9oZWFkPlxuICAgICAgPGJvZHk+XG4gICAgICAgIDxkaXYgaWQ9XCJyb290XCI+JHtvcHRzLmJvZHl9PC9kaXY+XG4gICAgICA8L2JvZHk+XG4gICAgICA8c2NyaXB0PlxuICAgICAgICB3aW5kb3cuX19pbml0aWFsU3RhdGUgPSAke29wdHMuaW5pdGlhbFN0YXRlfVxuICAgICAgPC9zY3JpcHQ+XG4gICAgICA8IS0tIENsaWVudCBidW5kbGUgZ2VuZXJhdGVkIGJ5IHdlYnBhY2sgLS0+XG4gICAgICA8c2NyaXB0IHNyYz0nL2Fzc2V0cy9jbGllbnQuYnVuZGxlLmpzJz48L3NjcmlwdD5cbiAgICA8L2h0bWw+XG4gICAgYDtcbn07XG5cbmV4cG9ydCBkZWZhdWx0IHRlbXBsYXRlO1xuIl19